#!/usr/bin/env python3
"""
Extract vertical YouTube Shorts clips from final_animation.mp4.

Reads shorts_plan.json (generated by Claude) for recommended shot ranges,
extracts those segments, and center-crops to 9:16 vertical format using FFmpeg.

Output: ./shorts/short_001.mp4, short_002.mp4, ...

Usage:
  cd /path/to/your/project

  # Extract all Shorts from the plan
  python ~/.claude/skills/youtube-publish-package/scripts/extract_shorts.py

  # Extract specific shot ranges (overrides the plan)
  python ~/.claude/skills/youtube-publish-package/scripts/extract_shorts.py --shots 3-6
  python ~/.claude/skills/youtube-publish-package/scripts/extract_shorts.py --shots 1-3 --shots 8-10

  # Extract a single shot as a Short
  python ~/.claude/skills/youtube-publish-package/scripts/extract_shorts.py --shots 5-5

Requirements:
  FFmpeg installed and in PATH
"""

import json
import subprocess
import argparse
from pathlib import Path


SHOT_DURATION = 8  # seconds per shot


# ── Helpers ──────────────────────────────────────────────────────────────────

def check_ffmpeg() -> bool:
    try:
        result = subprocess.run(
            ["ffmpeg", "-version"], capture_output=True, text=True,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def extract_short(input_path: Path, output_path: Path,
                  start_sec: float, duration_sec: float) -> bool:
    """Extract a segment and center-crop to 9:16 vertical."""
    cmd = [
        "ffmpeg", "-y",
        "-i", str(input_path),
        "-ss", str(start_sec),
        "-t", str(duration_sec),
        "-vf", "crop=ih*9/16:ih",
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-c:a", "aac",
        "-b:a", "128k",
        str(output_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"    FFmpeg error: {result.stderr[-500:]}")
        return False
    return output_path.exists() and output_path.stat().st_size > 0


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Extract vertical YouTube Shorts from final_animation.mp4."
    )
    parser.add_argument(
        "--shots", action="append", metavar="START-END",
        help="Shot range to extract (e.g., 3-6). Can be repeated. "
             "Overrides shorts_plan.json.",
    )
    args = parser.parse_args()

    print("\n=== Story-to-Animation: Step 6 — YouTube Shorts Extraction ===\n")

    # ── Validate prerequisites ─────────────────────────────────────────────────
    if not check_ffmpeg():
        print("ERROR: FFmpeg not found in PATH.")
        print("  Windows : winget install ffmpeg")
        print("  Mac     : brew install ffmpeg")
        print("  Linux   : sudo apt install ffmpeg")
        raise SystemExit(1)

    animation_path = Path("final_animation.mp4")
    if not animation_path.exists():
        print("ERROR: final_animation.mp4 not found — run Step 5 first.")
        raise SystemExit(1)

    if not Path("shots.json").exists():
        print("ERROR: shots.json not found.")
        raise SystemExit(1)

    shots_data = json.loads(Path("shots.json").read_text(encoding="utf-8"))
    total_shots = len(shots_data.get("shots", []))

    if total_shots == 0:
        print("ERROR: No shots found in shots.json.")
        raise SystemExit(1)

    # ── Build extraction plan ──────────────────────────────────────────────────
    shorts_to_extract = []

    if args.shots:
        # Parse command-line shot ranges
        for i, range_str in enumerate(args.shots, 1):
            parts = range_str.split("-")
            if len(parts) == 2:
                start_shot = int(parts[0])
                end_shot = int(parts[1])
            elif len(parts) == 1:
                start_shot = end_shot = int(parts[0])
            else:
                print(f"ERROR: Invalid range '{range_str}'. Use START-END (e.g., 3-6).")
                raise SystemExit(1)

            if start_shot < 1 or end_shot > total_shots:
                print(f"ERROR: Shot range {start_shot}-{end_shot} out of bounds (1-{total_shots}).")
                raise SystemExit(1)

            shorts_to_extract.append({
                "short_id": f"short_{i:03d}",
                "title": f"Shots {start_shot}-{end_shot}",
                "shot_range": [start_shot, end_shot],
                "caption": "",
            })
    else:
        # Read from shorts_plan.json
        plan_path = Path("shorts_plan.json")
        if not plan_path.exists():
            print("ERROR: shorts_plan.json not found.")
            print("  Claude should generate this file before running the script.")
            print("  Or use --shots to specify ranges manually (e.g., --shots 3-6).\n")
            raise SystemExit(1)

        plan = json.loads(plan_path.read_text(encoding="utf-8"))
        shorts_to_extract = plan.get("shorts", [])

    if not shorts_to_extract:
        print("ERROR: No Shorts defined in the plan.")
        raise SystemExit(1)

    # ── Extract ────────────────────────────────────────────────────────────────
    shorts_dir = Path("shorts")
    shorts_dir.mkdir(exist_ok=True)

    results = {"success": [], "failed": []}

    print(f"  Total shots in animation : {total_shots}")
    print(f"  Shorts to extract        : {len(shorts_to_extract)}")
    print(f"  Output format            : 9:16 vertical (center-cropped)\n")

    for short in shorts_to_extract:
        sid = short["short_id"]
        shot_range = short["shot_range"]
        start_shot = shot_range[0]
        end_shot = shot_range[1]

        # Calculate time boundaries (shots are 1-indexed, each 8 seconds)
        start_sec = (start_shot - 1) * SHOT_DURATION
        num_shots = end_shot - start_shot + 1
        duration_sec = num_shots * SHOT_DURATION

        if duration_sec > 60:
            print(f"  [{sid}] WARNING: {duration_sec}s exceeds 60s Shorts limit — trimming to 60s")
            duration_sec = 60

        output_path = shorts_dir / f"{sid}.mp4"

        title = short.get("title", "")
        print(f"  [{sid}] shots {start_shot}-{end_shot} ({duration_sec}s) — {title}")

        if output_path.exists():
            print(f"         already exists — skipping (delete to re-extract)")
            results["success"].append(sid)
            continue

        if extract_short(animation_path, output_path, start_sec, duration_sec):
            size_kb = output_path.stat().st_size / 1024
            print(f"         saved ({size_kb:.0f} KB)")
            results["success"].append(sid)
        else:
            print(f"         FAILED")
            results["failed"].append(sid)

    # ── Summary ────────────────────────────────────────────────────────────────
    print(f"\n{'='*50}")
    print(f"  Extracted : {len(results['success'])} Shorts → ./shorts/")
    print(f"  Failed    : {len(results['failed'])}")
    print(f"{'='*50}")

    if results["failed"]:
        print("\nFailed Shorts:")
        for sid in results["failed"]:
            print(f"  - {sid}")
        raise SystemExit(1)
    else:
        print("\nAll Shorts extracted!")
        print("Upload each as a YouTube Short with the title and caption from publish.md.\n")


if __name__ == "__main__":
    main()
