#!/usr/bin/env python3
"""
Generate a YouTube-optimized thumbnail image via Replicate API.

Reads thumbnail_brief.json (generated by Claude) and creates an eye-catching
thumbnail featuring the main character in an expressive close-up pose.

Output: ./thumbnail.png (16:9 aspect ratio, optimized for YouTube 1280x720)

Config — uses REPLICATE_API_TOKEN from .env (same key as other pipeline scripts).

Usage:
  cd /path/to/your/project
  python ~/.claude/skills/youtube-publish-package/scripts/generate_thumbnail.py

  # Use a different model
  python ~/.claude/skills/youtube-publish-package/scripts/generate_thumbnail.py --model ideogram-ai/ideogram-v2

  # Override the prompt directly
  python ~/.claude/skills/youtube-publish-package/scripts/generate_thumbnail.py --prompt "custom prompt here"

Requirements:
  pip install requests
"""

import os
import json
import time
import argparse
from pathlib import Path
import requests


REPLICATE_API_BASE = "https://api.replicate.com/v1"
DEFAULT_MODEL = "black-forest-labs/flux-1.1-pro"
POLL_INTERVAL = 5
MAX_POLLS = 60


# ── Config loading (.env) ─────────────────────────────────────────────────────

def load_env() -> None:
    env_path = Path(".env")
    if not env_path.exists():
        print("\nERROR: .env file not found in current directory.")
        print("  This script shares the same .env as the rest of the pipeline.")
        print("  Create .env with: REPLICATE_API_TOKEN=your_token_here\n")
        raise SystemExit(1)

    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key, val = key.strip(), val.strip()
        if key and key not in os.environ:
            os.environ[key] = val


load_env()

REPLICATE_API_TOKEN = os.environ.get("REPLICATE_API_TOKEN", "").strip()
if not REPLICATE_API_TOKEN or REPLICATE_API_TOKEN.startswith("your_"):
    print("\nERROR: REPLICATE_API_TOKEN not set in .env")
    raise SystemExit(1)

AUTH_HEADER = {"Authorization": f"Bearer {REPLICATE_API_TOKEN}"}


# ── Replicate API helpers ─────────────────────────────────────────────────────

def submit_prediction(model_id: str, input_payload: dict) -> tuple:
    try:
        resp = requests.post(
            f"{REPLICATE_API_BASE}/predictions",
            headers={**AUTH_HEADER, "Content-Type": "application/json"},
            json={"model": model_id, "input": input_payload},
            timeout=30,
        )
        data = resp.json()
        if resp.status_code in (200, 201) and data.get("id"):
            return data["id"], None
        return None, f"HTTP {resp.status_code}: {data.get('detail', data.get('error', str(data)))}"
    except Exception as e:
        return None, str(e)


def poll_prediction(prediction_id: str) -> tuple:
    url = f"{REPLICATE_API_BASE}/predictions/{prediction_id}"
    for attempt in range(1, MAX_POLLS + 1):
        time.sleep(POLL_INTERVAL)
        try:
            resp = requests.get(url, headers=AUTH_HEADER, timeout=30)
            data = resp.json()
            status = data.get("status", "")

            if status == "succeeded":
                output = data.get("output")
                if isinstance(output, str):
                    return output, None
                elif isinstance(output, list) and output:
                    return output[0], None
                return None, f"Unexpected output format: {output}"
            elif status == "failed":
                return None, data.get("error", "Prediction failed")
            elif status == "canceled":
                return None, "Prediction was canceled"
            else:
                elapsed = attempt * POLL_INTERVAL
                if elapsed % 30 == 0:
                    print(f"  [thumbnail] {status or 'starting'} — {elapsed}s elapsed...")
        except Exception as e:
            print(f"  [thumbnail] poll error: {e}")

    return None, f"Timed out after {MAX_POLLS * POLL_INTERVAL}s"


def download_file(url: str, output_path: Path) -> bool:
    try:
        resp = requests.get(url, timeout=60)
        output_path.write_bytes(resp.content)
        return output_path.stat().st_size > 0
    except Exception as e:
        print(f"  Download failed: {e}")
        return False


def upload_to_replicate_files(local_path: Path) -> tuple:
    try:
        with open(local_path, "rb") as f:
            resp = requests.post(
                f"{REPLICATE_API_BASE}/files",
                headers=AUTH_HEADER,
                files={"content": (local_path.name, f, "image/png")},
                timeout=60,
            )
        data = resp.json()
        if resp.status_code in (200, 201):
            url = data.get("urls", {}).get("get") or data.get("url")
            if url:
                return url, None
            return None, f"No URL in response: {data}"
        return None, f"HTTP {resp.status_code}: {data}"
    except Exception as e:
        return None, str(e)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate a YouTube thumbnail via Replicate API."
    )
    parser.add_argument(
        "--model", default=DEFAULT_MODEL,
        help=f"Replicate model to use (default: {DEFAULT_MODEL}).",
    )
    parser.add_argument(
        "--prompt", default=None,
        help="Override the prompt from thumbnail_brief.json.",
    )
    args = parser.parse_args()

    print("\n=== Story-to-Animation: Step 6 — YouTube Thumbnail ===\n")

    output_path = Path("thumbnail.png")
    if output_path.exists():
        print("  thumbnail.png already exists — delete it to regenerate.")
        return

    # ── Load prompt ────────────────────────────────────────────────────────────
    if args.prompt:
        prompt = args.prompt
        print(f"  Using command-line prompt override.\n")
    else:
        brief_path = Path("thumbnail_brief.json")
        if not brief_path.exists():
            print("ERROR: thumbnail_brief.json not found.")
            print("  Claude should generate this file before running the script.")
            print("  Or use --prompt to provide a prompt directly.\n")
            raise SystemExit(1)

        brief = json.loads(brief_path.read_text(encoding="utf-8"))
        prompt = brief.get("prompt", "")
        if not prompt:
            print("ERROR: 'prompt' field is empty in thumbnail_brief.json")
            raise SystemExit(1)

        char_name = brief.get("character_name", "character")
        text_hint = brief.get("text_overlay_suggestion", "")
        print(f"  Character : {char_name}")
        print(f"  Text hint : {text_hint}")
        print(f"  Model     : {args.model}\n")

    # ── Generate ───────────────────────────────────────────────────────────────
    input_payload = {
        "prompt": prompt,
        "aspect_ratio": "16:9",
    }
    if "flux" in args.model:
        input_payload["output_format"] = "png"

    print("  Submitting thumbnail generation...")
    pred_id, err = submit_prediction(args.model, input_payload)
    if not pred_id:
        print(f"  FAILED: {err}")
        raise SystemExit(1)

    print(f"  Prediction: {pred_id[:16]}...\n")

    gen_url, err = poll_prediction(pred_id)
    if not gen_url:
        print(f"  FAILED: {err}")
        raise SystemExit(1)

    # ── Download ───────────────────────────────────────────────────────────────
    if not download_file(gen_url, output_path):
        print("  Download failed.")
        raise SystemExit(1)

    # ── Upload to Replicate Files ──────────────────────────────────────────────
    file_url, err = upload_to_replicate_files(output_path)
    if file_url:
        print(f"  Hosted at: {file_url}")
    else:
        print(f"  Files API upload failed ({err}) — local file still saved.")

    # ── Summary ────────────────────────────────────────────────────────────────
    size_kb = output_path.stat().st_size / 1024
    print(f"\n{'='*50}")
    print(f"  Output : ./thumbnail.png ({size_kb:.0f} KB)")
    print(f"  Model  : {args.model}")
    print(f"{'='*50}")
    print("\n  Next: add text overlay in Canva (free) or similar tool.")
    print("  Recommended size: 1280 x 720 pixels.\n")


if __name__ == "__main__":
    main()
